### ISSUE TITLE
let expoered json schema support unhandled meta info

### ISSUE THREAD

**Issue by bluelovers** [sodaru/yup-to-json-schema#10]
expected

```js
jsonSchema.meta = shape.spec.meta
```

**Comment by Raaghu** [comment]
@bluelovers is the keyword `meta` is supported by JSON Schema. Point to specifications/documentation/reference about `meta` in JSON Schema or any JSON Schema Libraries.

**Comment by bluelovers** [comment]
i don't know, but `ajv` is allow add it

**Comment by Raaghu** [comment]
I need some time implement this

**Comment by Raaghu** [comment]
Duplicate of #11
