### ISSUE TITLE
Merge additional info from meta()

### ISSUE THREAD

**Issue by DaddyWarbucks** [sodaru/yup-to-json-schema#11]
It would be helpful if the metadata helper merged additional properties onto the JSON Schema. https://github.com/sodaru/yup-to-json-schema/blob/main/src/converters/commonMetadata.ts should be updated to merge `shape.spec.meta.jsonSchema` properties onto the `jsonSchema`.
For example
```js
if (shape.spec.meta?.jsonSchema) {
  Object.assign(jsonSchema, shape.spec.meta.jsonSchema);
}
```
This would allow the user to pass any arbitrary keys to `.meta({ jsonSchema: { ... } })` which would allow them to customize this library while still keeping the library JSON Schema compliant.

I am using Swagger to create a docs website. Swagger supports the `example` and `examples` keywords, even though `example` is no longer valid. With this update, I could still use `example` with the following:
```js
yup.object({
  name: yup.string().meta({ jsonSchema: { example: 'DaddyWarbucks' } })
})
```

**Comment by Raaghu** [comment]
merged and releases as part of https://github.com/sodaru/yup-to-json-schema/tree/v1.1.1
