### ISSUE TITLE
Support Yup V1

### ISSUE THREAD

**Issue by DaddyWarbucks** [sodaru/yup-to-json-schema#13]
I've got working version of support for Yup V1 on my forked repo that I plan to open a PR for soon. This is a full rewrite and may require a major version. I actually got a few PR's merged in Yup specifically for this case. See : https://github.com/jquense/yup/pull/1887

- Supports `nullable()`
- Support for the new `getDefault()`
- Better `required()` support with how Yup V1 changed. It now has an `optional` flag instead of relying on the `tests` array.
- General cleanup and type improvements.
- Relies solely on the result of `describe()` instead of digging around in schema internals
- Various other bug fixes and improvements found along the way.

PR coming soon!

**Comment by Raaghu** [comment]
You are welcome, Lets plan it for a major release then

**Comment by ghost** [comment]
When is this pull request ready @DaddyWarbucks? We're currently implementing this yup-to-json-schema repo although without v1 support it's unusable.

**Comment by DaddyWarbucks** [comment]
Sorry. I was traveling in February and did not have time for this. I will try to finalize it over the weekend.

**Comment by zolero** [comment]
> Sorry. I was traveling in February and did not have time for this. I will try to finalize it over the weekend.

If you need any help let me know.

**Comment by DaddyWarbucks** [comment]
Sorry I have been slow to respond on this! Please see the attached PR. It is basically a full rewrite to handle Yup v1 and offers a few additional methods.

**Comment by Raaghu** [comment]
Thanks @DaddyWarbucks for the contribution. Released the new version with your changes to NPM https://www.npmjs.com/package/@sodaru/yup-to-json-schema/v/2.0.0
